---

- name: Run equivalent of apt-get update and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Install prerequisites 
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - openjdk-8-jre-headless
    - uuid-runtime
    - pwgen

- name: Add MongoDB apt-key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4
    state: present

- name: Add MongoDB apt repository
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse
    state: present
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Enable MongoDB during system start up
  systemd:
    name: mongod
    enabled: yes
    state: restarted