---

# - name: trigger handlers
#   meta: flush_handlers
    # - apt-get update
    # - apt-get upgrade


- name: Install prerequisites 
  apt:
    name: apache2
    state: present
    # update_cache: yes
  notify: apt-get update
  # vars:
  #   packages:
  #     - apt-transport-https
  #     - openjdk-8-jre-headless
  #     - uuid-runtime
  #     - pwgen

# - name: Add MongoDB apt-key
#   apt_key:
#     keyserver: hkp://keyserver.ubuntu.com:80
#     id: 9DA31620334BD75D9DCB49F368818C72E52529D4
#     state: present

# - name: Add MongoDB apt repository
#   apt_repository:
#     repo: https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse
#     state: present
#     update_cache: yes

    # - name: MongoDB command
    #   command: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

    # - name: Install MongoDB
    #   apt:
    #     name: mongodb-org
    #     state: present
    #     update_cache: yes
