---
- name: Create EC2 instance
  ec2:
    key_name: '{{ key_name }}'
    instance_type: t2.micro
    image: '{{ ami_id }}'
    vpc_subnet_id: '{{ subnet_id }}'
    assign_public_ip: yes
    region: '{{ region }}'
    user_data: "{{ lookup('file', 'userdata.sh') }}"